# Generated by Django 5.0.2 on 2024-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='tekst',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
