# Generated by Django 5.0.2 on 2024-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cards_tekst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
